version: "3.8"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"

  web:
    build: .
    command: fastapi dev app/main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env